### ISSUE TITLE
Nginx 403/404

### ISSUE THREAD

**Issue by mindovermiles262** [pi0/osticket-docker#1]
I've installed this docker container via the instructed methods including the MariaDB.

When I try to go to `http://localhost:8080` I get a 403 restricted.
`http://localhost:8080/scp` gives me a 404

Nginx logs in /var/www/logs/nginx-error.log as follows:

    # cat nginx-error.log 
    2018/07/03 01:38:17 [error] 40#40: *1 directory index of "/var/www/src/public/" is forbidden, client: 172.17.0.1, server: _, request: "GET / HTTP/1.1", host: "localhost:8080"
    2018/07/03 01:38:17 [error] 40#40: *1 open() "/var/www/src/public/favicon.ico" failed (2: No such file or directory), client: 172.17.0.1, server: _, request: "GET /favicon.ico HTTP/1.1", host: "localhost:8080"
    2018/07/03 01:38:17 [error] 40#40: *1 open() "/var/www/src/public/favicon.ico" failed (2: No such file or directory), client: 172.17.0.1, server: _, request: "GET /favicon.ico HTTP/1.1", host: "localhost:8080"
    2018/07/03 01:41:52 [error] 40#40: *3 directory index of "/var/www/src/public/" is forbidden, client: 172.17.0.1, server: _, request: "GET / HTTP/1.1", host: "0.0.0.0:8080"
    2018/07/03 01:41:52 [error] 40#40: *3 open() "/var/www/src/public/favicon.ico" failed (2: No such file or directory), client: 172.17.0.1, server: _, request: "GET /favicon.ico HTTP/1.1", host: "0.0.0.0:8080"
    2018/07/03 01:41:52 [error] 40#40: *3 open() "/var/www/src/public/favicon.ico" failed (2: No such file or directory), client: 172.17.0.1, server: _, request: "GET /favicon.ico HTTP/1.1", host: "0.0.0.0:8080"
    2018/07/03 01:45:32 [error] 40#40: *4 directory index of "/var/www/src/public/" is forbidden, client: 172.17.0.1, server: _, request: "GET / HTTP/1.1", host: "0.0.0.0:8080"
    2018/07/03 01:47:21 [error] 40#40: *4 FastCGI sent in stderr: "PHP message: PHP Parse error:  syntax error, unexpected 'echo' (T_ECHO), expecting ',' or ';' in /bin/webhook.php on line 12" while reading response header from upstream, client: 172.17.0.1, server: _, request: "GET /webhook.php HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.0-fpm.sock:", host: "0.0.0.0:8080"

Any suggestions what I'm doing wrong?

EDIT: See also https://stackoverflow.com/questions/51145679/docker-osticket-http-errors

**Comment by Capobuf** [comment]
> I've installed this docker container via the instructed methods including the MariaDB.
> 
> When I try to go to `http://localhost:8080` I get a 403 restricted.
> `http://localhost:8080/scp` gives me a 404
> 
> Nginx logs in /var/www/logs/nginx-error.log as follows:
> 
> ```
> # cat nginx-error.log 
> 2018/07/03 01:38:17 [error] 40#40: *1 directory index of "/var/www/src/public/" is forbidden, client: 172.17.0.1, server: _, request: "GET / HTTP/1.1", host: "localhost:8080"
> 2018/07/03 01:38:17 [error] 40#40: *1 open() "/var/www/src/public/favicon.ico" failed (2: No such file or directory), client: 172.17.0.1, server: _, request: "GET /favicon.ico HTTP/1.1", host: "localhost:8080"
> 2018/07/03 01:38:17 [error] 40#40: *1 open() "/var/www/src/public/favicon.ico" failed (2: No such file or directory), client: 172.17.0.1, server: _, request: "GET /favicon.ico HTTP/1.1", host: "localhost:8080"
> 2018/07/03 01:41:52 [error] 40#40: *3 directory index of "/var/www/src/public/" is forbidden, client: 172.17.0.1, server: _, request: "GET / HTTP/1.1", host: "0.0.0.0:8080"
> 2018/07/03 01:41:52 [error] 40#40: *3 open() "/var/www/src/public/favicon.ico" failed (2: No such file or directory), client: 172.17.0.1, server: _, request: "GET /favicon.ico HTTP/1.1", host: "0.0.0.0:8080"
> 2018/07/03 01:41:52 [error] 40#40: *3 open() "/var/www/src/public/favicon.ico" failed (2: No such file or directory), client: 172.17.0.1, server: _, request: "GET /favicon.ico HTTP/1.1", host: "0.0.0.0:8080"
> 2018/07/03 01:45:32 [error] 40#40: *4 directory index of "/var/www/src/public/" is forbidden, client: 172.17.0.1, server: _, request: "GET / HTTP/1.1", host: "0.0.0.0:8080"
> 2018/07/03 01:47:21 [error] 40#40: *4 FastCGI sent in stderr: "PHP message: PHP Parse error:  syntax error, unexpected 'echo' (T_ECHO), expecting ',' or ';' in /bin/webhook.php on line 12" while reading response header from upstream, client: 172.17.0.1, server: _, request: "GET /webhook.php HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.0-fpm.sock:", host: "0.0.0.0:8080"
> ```
> Any suggestions what I'm doing wrong?
> 
> EDIT: See also https://stackoverflow.com/questions/51145679/docker-osticket-http-errors

Same Problem

**Comment by jocarren** [comment]
Same here.

**Comment by maikeldotuk** [comment]
Same issue here, rendering this docker image useless.

**Comment by kiuka** [comment]
the docker image does not clone the repository or contains the source code in it. I just faced the same issues, how should this even work lol

**Comment by elekgeek** [comment]
same here in June 2020!

**Comment by sknopp** [comment]
found that ```/etc/nginx/conf.d/default.conf``` is pointing to the wrong directory as www-root. 

line 10 should look as follows. 
```ini
    [...]
    # The location of our projects public directory.
    root /var/www/src/;
    [...]
```

but as stated by the author in #6 unfortunately this here is no longer maintained and therefore i'll look for another image.
