### ISSUE TITLE
New Docker Hub image

### ISSUE THREAD

**Issue by abelland** [pi0/osticket-docker#6]
Could you please update the [Docker Hub image](https://hub.docker.com/r/osticket/osticket/dockerfile) with the latest update that you have done? 

`Set permissions /bin/vendor to be root:www-data and 770 (#5)`

Thanks

**Comment by aneurinprice** [comment]
@abelland Not sure of it is of interest to you, but I will be working on a an actively maintained version of osticket for docker. Doing things in a way that I feel is more simple and clean. It'll be on my gitlab and here in a few days time. Input is welcome.

**Comment by pi0** [comment]
@abelland I've updated Dockerfile. 

@aneurinprice I would be happy to transfer you access of `osticket/osticket` docker image. I'm no longer working on this. Also, It would be great if we can transfer repo to [osticket](https://github.com/osTicket) official org. I'll contact maintainers.
