### ISSUE TITLE
Unable to change de Admin password

### ISSUE THREAD

**Issue by Javit96** [pi0/osticket-docker#9]
I can install succesfully the system, but when i try to change the password of the admin user a pop with the home url is blocking and i can´t change the pass
![ostadmin](https://user-images.githubusercontent.com/49079518/94701259-d43d1680-0312-11eb-8747-1bbc7a8cf8ca.jpg)

**Comment by sknopp** [comment]
Hi,

i can confirm this behaviour and digged a bit into it. It seems like every tooltip page of osTicket which is loaded asynchronously through `/scp/ajax.php/[...]` is just redirected to `/` for some reason (in this case `/scp/ajax.php/staff/1/set-password`). Another example is the detailled log view.

Maybe it is just a routing problem in nginx. I did not have the time to look on it..

Interestingly also the help tooltips (the small "`?`" on some configuration parameters) do not work, but they do not seem to load something from `ajax.php`. But that could also be another issue..

**Comment by sknopp** [comment]
I got it working and will make a PR with the needed configuration changes. Essentially I found [this here](https://github.com/osTicket/osTicket/issues/4753#issuecomment-466431480) and followed the instructions.

Unfortunately this image bases on nginx which is not officially supported by now (what makes it even more funny that this here is referred by the osticket account as some kind official on Docker Hub).

The config changes seem to be pretty common, i found them multiple times with some variations, so i hope they work good enough. (But at least they do better than now)

**Comment by cagianx** [comment]
hello,
if you're in a hurry I've solved it by replacing the file `/etc/nginx/conf.d/default.conf` (inside the container) with the pull-request file [https://github.com/pi0/osticket-docker/blob/29d500ad61535bff81b0ac0bd4350cd0027be18d/conf/default.conf](https://github.com/pi0/osticket-docker/blob/29d500ad61535bff81b0ac0bd4350cd0027be18d/conf/default.conf)

The password change windows (and tooltips) have started to work correctly

**Comment by Javit96** [comment]
Hi! 

I saw the commit that you made @sknopp. 
Thanks!! I´m gonna try with the change that you made and i'll leave you the response if this works or not, on my system.

**Comment by likuilin** [comment]
Ran into the same issue, and the provided fix successfully fixed it. Could this be merged, please, maintainers?
